--- #YAML:1.0
name:                URI-ParseSearchString
version:             0.10
abstract:            parse Apache refferer logs and extract search engine query strings.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Spiros Denaxas <spiros@lokku.com>
